# permissions for end users to edit kscalepods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kscalepod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kscalepod
    app.kubernetes.io/part-of: kscalepod
    app.kubernetes.io/managed-by: kustomize
  name: kscalepod-editor-role
rules:
- apiGroups:
  - app.cumulonimbus.ai
  resources:
  - kscalepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cumulonimbus.ai
  resources:
  - kscalepods/status
  verbs:
  - get
