---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.cumulonimbus.ai
  resources:
  - kscalepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.cumulonimbus.ai
  resources:
  - kscalepods/finalizers
  verbs:
  - update
- apiGroups:
  - app.cumulonimbus.ai
  resources:
  - kscalepods/status
  verbs:
  - get
  - patch
  - update
